/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartContainer: typeof import('./../../components/chartContainer.vue')['default']
    DrawLine: typeof import('./../../components/drawLine.vue')['default']
    DrawLine1: typeof import('./../../components/drawLine1.vue')['default']
    DrawSensor: typeof import('./../../components/drawSensor.vue')['default']
    DrawY: typeof import('./../../components/drawY.vue')['default']
    EchartsLine1: typeof import('./../../components/echarts/line1.vue')['default']
    EchartsLine2: typeof import('./../../components/echarts/line2.vue')['default']
    EchartsLine3: typeof import('./../../components/echarts/line3.vue')['default']
    EchartsPie: typeof import('./../../components/echarts/pie.vue')['default']
    EchartsTest_echarts: typeof import('./../../components/echarts/test_echarts.vue')['default']
    EchartsTest_echarts1: typeof import('./../../components/echarts/test_echarts1.vue')['default']
    HeadMenu: typeof import('./../../components/HeadMenu.vue')['default']
    HelloWorld: typeof import('./../../components/HelloWorld.vue')['default']
    Login: typeof import('./../../components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensorAPIData: typeof import('./../../components/sensorAPIData.vue')['default']
    SensorDashboard: typeof import('./../../components/sensorDashboard.vue')['default']
    Sidebar: typeof import('./../../components/sidebar.vue')['default']
    Statistic: typeof import('./../../components/statistic.vue')['default']
    StatusIcon: typeof import('./../../components/StatusIcon.vue')['default']
    Test_copilot: typeof import('./../../components/test_copilot.vue')['default']
    ToggleTheme: typeof import('./../../components/ToggleTheme.vue')['default']
    TransferStation: typeof import('./../../components/TransferStation.vue')['default']
  }
}
